"""Explicit import of complete legacy FC chains; no mutable mapper execution.

Sidecar tensors assert the normalized dense/tiled logical shape and storage.
Legacy slices verify element counts and matching load/store extents, never infer
bytes, axis flattening, physical workers, conversions or compute rates.
"""

from __future__ import annotations

import math
from typing import Annotated, Literal, Self

from pydantic import Field, StrictBool, model_validator

from .compute_plan import ComputePlan
from .configs.schemas.compute_workload import ComputeImportProvenance, ComputeWorkload
from .configs.schemas.topology import (
    GraphRecord,
    Identifier,
    Index,
    PositiveInt,
    unique,
)
from .topology import content_digest
from .utils.dfg import DFG


class LegacySlice(GraphRecord):
    start: Index
    end: PositiveInt

    @model_validator(mode="after")
    def nonempty(self) -> Self:
        if self.end <= self.start:
            raise ValueError("legacy FC slices must have positive extents")
        return self


class LegacyFCNode(GraphRecord):
    index: Index
    operation: Literal["LOAD_FEAT", "LOAD_WGT", "FC", "STORE"]
    core_id: Index
    input_size: tuple[LegacySlice, ...]
    weight_size: tuple[LegacySlice, ...]
    output_size: tuple[LegacySlice, ...]
    parent: tuple[Index, ...]
    child: tuple[Index, ...]
    fabric_id: Index
    nmc_shape_mode: Literal["static", "dynamic"]
    received_input: Index
    received_weight: Index
    ready: StrictBool
    executed: StrictBool
    finished: StrictBool

    @model_validator(mode="after")
    def edges(self) -> Self:
        unique(self.parent, "legacy parent")
        unique(self.child, "legacy child")
        return self


class LegacyFCSnapshot(GraphRecord):
    nodes: tuple[LegacyFCNode, ...] = Field(min_length=1)

    @classmethod
    def capture(cls, dfg: DFG) -> LegacyFCSnapshot:
        nodes: list[LegacyFCNode] = []
        for index, node in sorted(dfg.nodes.items()):
            if index != node.index:
                raise ValueError("legacy DFG key differs from node identity")
            nodes.append(LegacyFCNode.model_validate({
                "index": node.index, "operation": node.operation.name, "core_id": node.core_id,
                "input_size": [s.model_dump(mode="python") for s in node.input_size],
                "weight_size": [s.model_dump(mode="python") for s in node.weight_size],
                "output_size": [s.model_dump(mode="python") for s in node.output_size],
                "parent": tuple(node.parent), "child": tuple(node.child), "fabric_id": int(node.fabric_id),
                "nmc_shape_mode": node.nmc_shape_mode.value,
                "received_input": node.received_input, "received_weight": node.received_weight,
                "ready": node.ready, "executed": node.executed, "finished": node.finished,
            }))
        return cls(nodes=tuple(nodes))


class LegacyFCChain(GraphRecord):
    job_id: Identifier
    load_feat: Index
    load_wgt: Index
    fc: Index
    store: Index


class LegacyWorkerBinding(GraphRecord):
    core_id: Index
    worker_tile_id: Identifier


class LegacyFCSidecar(GraphRecord):
    kind: Literal["legacy_fc_chain_v1"]
    schema_version: Annotated[int, Field(strict=True, ge=1, le=1)]
    shape_interpretation: Literal["explicit_element_count_reshape_v1"]
    workers: tuple[LegacyWorkerBinding, ...] = Field(min_length=1)
    chains: tuple[LegacyFCChain, ...] = Field(min_length=1)
    workload: ComputeWorkload

    @model_validator(mode="after")
    def identities(self) -> Self:
        unique(tuple(w.core_id for w in self.workers), "legacy core binding")
        unique(tuple(w.worker_tile_id for w in self.workers), "legacy worker binding")
        unique(tuple(c.job_id for c in self.chains), "legacy imported job")
        unique(tuple(index for c in self.chains for index in (c.load_feat, c.load_wgt, c.fc, c.store)), "legacy imported node")
        if self.workload.legacy_import is not None:
            raise ValueError("legacy import provenance is generated by the adapter, not the sidecar")
        return self


def import_legacy_fc(dfg: DFG, sidecar: LegacyFCSidecar, source_document: object) -> ComputePlan:
    """Validate an immutable snapshot and return a pure, explicitly bound plan.

    Imports disjoint complete chains, with finite execution order supplied by
    sidecar streams. Extra graph edges, fanout/reuse and partial reductions do
    not fit this policy. Readiness flags are captured, not executed or changed.
    Memory lowering/runtime remain separate admission steps.
    """
    sidecar = LegacyFCSidecar.model_validate(sidecar.model_dump(mode="python"))
    snapshot = LegacyFCSnapshot.capture(dfg)
    nodes = {node.index: node for node in snapshot.nodes}
    used = {index for chain in sidecar.chains for index in (chain.load_feat, chain.load_wgt, chain.fc, chain.store)}
    jobs = {job.job_id: (stream, job) for stream in sidecar.workload.streams for job in stream.jobs}
    workers = {worker.core_id: worker.worker_tile_id for worker in sidecar.workers}
    if used != set(nodes) or {c.job_id for c in sidecar.chains} != set(jobs):
        raise ValueError("legacy FC sidecar must account for every DFG node and workload job exactly once")
    if set(workers) != {n.core_id for n in nodes.values()}:
        raise ValueError("legacy worker bindings must exactly cover imported cores")
    for chain in sidecar.chains:
        feature, weight, fc, store = (nodes[i] for i in (chain.load_feat, chain.load_wgt, chain.fc, chain.store))
        stream, job = jobs[chain.job_id]
        if tuple(n.operation for n in (feature, weight, fc, store)) != ("LOAD_FEAT", "LOAD_WGT", "FC", "STORE"):
            raise ValueError(f"job {chain.job_id}: node roles do not form an FC chain")
        expected = ((feature, (), (fc.index,)), (weight, (), (fc.index,)),
                    (fc, (feature.index, weight.index), (store.index,)), (store, (fc.index,), ()))
        for node, parents, children in expected:
            if set(node.parent) != set(parents) or set(node.child) != set(children):
                raise ValueError(f"node {node.index}: unmatched edge, fanout, reuse or partial reduction is unsupported")
            if node.core_id != fc.core_id or workers[node.core_id] != stream.worker_tile_id:
                raise ValueError(f"node {node.index}: explicit physical worker binding disagrees with its FC chain")
        if job.operation.kind != "fc" or job.depends_on or job.a.version.kind != "initial" or job.b.version.kind != "initial":
            raise ValueError("legacy FC chains require explicit FC shapes and independent initialized inputs")
        if (feature.input_size != fc.input_size or weight.weight_size != fc.weight_size or store.output_size != fc.output_size
                or feature.weight_size or feature.output_size or weight.input_size or weight.output_size
                or store.input_size or store.weight_size):
            raise ValueError(f"job {chain.job_id}: load/store tensor extents do not match its complete FC")
        for slices, tensor in ((fc.input_size, job.operation.a), (fc.weight_size, job.operation.b), (fc.output_size, job.operation.c)):
            if not slices or math.prod(s.end - s.start for s in slices) != math.prod(tensor.shape):
                raise ValueError(f"job {chain.job_id}: explicit reshape element count differs from legacy slices")
    provenance = ComputeImportProvenance(kind="legacy_fc_chain_v1", dfg_sha256=content_digest(snapshot.model_dump(mode="json")),
                                         sidecar_sha256=content_digest(sidecar.model_dump(mode="json")))
    config = sidecar.workload.model_copy(update={"legacy_import": provenance})
    return ComputePlan.compile(config, source_document)
